### ISSUE TITLE
Bug nevergrad

### ISSUE THREAD

**Issue by teytaud** [rdturnermtl/bbo_challenge_starter_kit#6]
As mentioned before the code was released,
the code uses a naive optimization method (the 1+1) rather than Nevergrad and was still calling this Nevergrad. This was on purpose for making the job easier for Bayesian Optimization tools, but it must be known that the code is wrong.
All independent comparisons I am aware of rank Nevergrad as vastly better than every Bayesian Optimization tool.

It would be nice if Bayesian Optimization was tested on BBOB or LSGO or other classical benchmarks.
For all my tests it is not competitive. We tested AX and many others: see the publicly available dashboard of Nevergrad.

**Comment by rdturnermtl** [comment]
I am closing this issue because:

1. This issue is ~1 yr out of date. It might have been relevant last summer. The challenge was during the summer of 2020, not summer of 2021.
2. This challenge has been adapted by other organizers to an everlasting benchmark on CodaLab. If you want to demonstrate the effectiveness of the methods in nevergrad, then go ahead and do it there: 
[https://competitions.codalab.org/competitions/28609](https://competitions.codalab.org/competitions/28609)
